#!/usr/bin/env python3
"""Builds the generated parts of the documentation set.

    python3 docs/build-docs.py

Reads   docs/srs/SRS-*.md          (requirements:  | FR-AREA-NNN | text | priority | source |)
        docs/tests/TC-*.md         (test cases:    #### TC-AREA-NNN — title  + "- **Requirement:** FR-…")
Writes  docs/tests/TC-INDEX.md             every test case in one table
        docs/05-TRACEABILITY.md            requirement -> test cases, coverage per area, gaps and unknown references
        docs/tests/execution-log-template.csv   one row per test case, to record a run
        docs/SRS-complete.md               all SRS parts in one file
and prints a summary. Nothing here is edited by hand: change the sources and run it again.
"""
import csv, glob, os, re, sys
from collections import defaultdict, OrderedDict

DOCS = os.path.dirname(os.path.abspath(__file__))
NFR_PARA = re.compile(r'^\*\*(NFR-[A-Z0-9]+-\d{3})\.?\*\*\.?\s*(.*)$')
REQ_ROW = re.compile(r'^\|\s*((?:FR|NFR)-[A-Z0-9]+-\d{3})\s*\|\s*(.*?)\s*\|\s*(Must|Should|Could)?\s*\|', re.I)
TC_HEAD = re.compile(r'^####\s+(TC-[A-Z0-9]+-\d{3})\s*[—–-]\s*(.+?)\s*$')
ID_IN_TEXT = re.compile(r'\b((?:N?FR)-[A-Z0-9]+-\d{3})\b')
SRS_ORDER = ['SRS-00-introduction.md', 'SRS-personal-a.md', 'SRS-personal-b.md', 'SRS-work.md', 'SRS-study.md', 'SRS-platform.md', 'SRS-99-appendices.md']
TC_ORDER = ['TC-personal-a.md', 'TC-personal-b.md', 'TC-work.md', 'TC-study.md', 'TC-platform.md']
MODE_OF = {'TC-personal-a.md': 'Personal', 'TC-personal-b.md': 'Personal', 'TC-work.md': 'Work', 'TC-study.md': 'Study', 'TC-platform.md': 'Platform'}


def read(path):
    with open(path, encoding='utf-8') as f:
        return f.read()


def parse_requirements():
    reqs = OrderedDict()   # id -> dict(text, priority, file, area)
    for name in SRS_ORDER:
        path = os.path.join(DOCS, 'srs', name)
        if not os.path.exists(path):
            continue
        for line in read(path).splitlines():
            p = NFR_PARA.match(line.strip())
            if p:   # a non-functional requirement written as a bold paragraph: **NFR-AREA-001.** text
                rid = p.group(1).upper()
                reqs[rid] = {'text': p.group(2), 'priority': '', 'file': name, 'area': rid.split('-')[1]}
                continue
            m = REQ_ROW.match(line)
            if m:
                rid = m.group(1).upper()
                reqs[rid] = {'text': m.group(2), 'priority': (m.group(3) or '').title(), 'file': name, 'area': rid.split('-')[1]}
    return reqs


def parse_cases():
    cases = OrderedDict()
    dupes = []
    for name in TC_ORDER:
        path = os.path.join(DOCS, 'tests', name)
        if not os.path.exists(path):
            continue
        cur = None
        for line in read(path).splitlines():
            h = TC_HEAD.match(line)
            if h:
                cur = {'id': h.group(1), 'title': h.group(2), 'file': name, 'mode': MODE_OF[name], 'reqs': [], 'type': '', 'prio': '', 'auto': ''}
                if cur['id'] in cases:
                    dupes.append(cur['id'])
                cases[cur['id']] = cur
                continue
            if line.startswith('## ') or line.startswith('# '):
                if cur and line.lower().startswith('## findings'):
                    cur = None
                continue
            if not cur:
                continue
            s = line.strip()
            if s.startswith('- **Requirement'):
                cur['reqs'] = [x.upper() for x in ID_IN_TEXT.findall(s)]
            elif s.startswith('- **Type'):
                v = s.split(':**', 1)[-1].strip()
                parts = [p.strip() for p in v.split('·')]
                cur['type'] = parts[0] if parts else ''
                cur['prio'] = parts[1] if len(parts) > 1 else ''
            elif s.startswith('- **Automation'):
                cur['auto'] = s.split(':**', 1)[-1].strip()
    return cases, dupes


def short_auto(a):
    a = re.sub(r'`', '', a)
    if not a:
        return ''
    low = a.lower()
    if low.startswith('manual'):
        return 'Manual'
    if low.startswith('device'):
        return 'Device only'
    return 'Automated' + (' (partly)' if ('otherwise' in low or 'manual' in low) else '')


def md_escape(s):
    return s.replace('|', '\\|')


def main():
    reqs = parse_requirements()
    cases, dupes = parse_cases()

    # requirement -> cases
    covers = defaultdict(list)
    unknown = defaultdict(list)
    no_req = []
    for c in cases.values():
        if not c['reqs']:
            no_req.append(c['id'])
        for r in c['reqs']:
            (covers if r in reqs else unknown)[r].append(c['id'])

    # ---- TC-INDEX.md
    out = ['# Test case index', '', f'Generated by `docs/build-docs.py` from `docs/tests/TC-*.md`. **{len(cases)} test cases.**', '']
    by_file = OrderedDict((n, []) for n in TC_ORDER)
    for c in cases.values():
        by_file[c['file']].append(c)
    out += ['| File | Mode | Cases | P1 | P2 | P3 |', '|---|---|---|---|---|---|']
    for n, lst in by_file.items():
        out.append(f"| [{n}]({n}) | {MODE_OF[n]} | {len(lst)} | {sum(1 for c in lst if c['prio'].startswith('P1'))} | {sum(1 for c in lst if c['prio'].startswith('P2'))} | {sum(1 for c in lst if c['prio'].startswith('P3'))} |")
    out.append('')
    for n, lst in by_file.items():
        if not lst:
            continue
        out += [f'## {n}', '', '| ID | Title | Type | Priority | Requirements | Automation |', '|---|---|---|---|---|---|']
        for c in lst:
            out.append(f"| [{c['id']}]({n}#{c['id'].lower()}) | {md_escape(c['title'])} | {c['type']} | {c['prio']} | {', '.join(c['reqs'])} | {short_auto(c['auto'])} |")
        out.append('')
    with open(os.path.join(DOCS, 'tests', 'TC-INDEX.md'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(out) + '\n')

    # ---- TRACEABILITY
    areas = OrderedDict()
    for rid, r in reqs.items():
        a = areas.setdefault(r['area'], {'n': 0, 'covered': 0, 'file': r['file']})
        a['n'] += 1
        a['covered'] += 1 if covers.get(rid) else 0
    t = ['# Traceability matrix', '',
         'Generated by `docs/build-docs.py`. Every requirement in `docs/srs/` is listed with the test cases that check it (from the **Requirement** line of each test case).', '',
         f'**{len(reqs)} requirements · {len(cases)} test cases · {sum(1 for r in reqs if covers.get(r))} requirements covered ({(100 * sum(1 for r in reqs if covers.get(r)) // max(1, len(reqs)))} %).**', '',
         '## Coverage by area', '', '| Area | SRS part | Requirements | With a test case | Coverage |', '|---|---|---|---|---|']
    for a, v in areas.items():
        t.append(f"| {a} | {v['file']} | {v['n']} | {v['covered']} | {100 * v['covered'] // max(1, v['n'])} % |")
    gaps = [r for r in reqs if not covers.get(r)]
    t += ['', '## Requirements without a test case', '']
    t += ([f'- {r} — {md_escape(reqs[r]["text"])[:110]}' for r in gaps] if gaps else ['None.'])
    t += ['', '## Test cases that point at an unknown requirement', '']
    t += ([f'- {r}: {", ".join(v)}' for r, v in sorted(unknown.items())] if unknown else ['None.'])
    t += ['', '## Test cases with no requirement line', '']
    t += ([f'- {c}' for c in no_req] if no_req else ['None.'])
    if dupes:
        t += ['', '## Duplicate test case IDs', ''] + [f'- {d}' for d in dupes]
    t += ['', '## Matrix', '', '| Requirement | Priority | Statement | Test cases |', '|---|---|---|---|']
    for rid, r in reqs.items():
        t.append(f"| {rid} | {r['priority']} | {md_escape(r['text'])[:140]} | {', '.join(covers.get(rid, [])) or '**none**'} |")
    with open(os.path.join(DOCS, '05-TRACEABILITY.md'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(t) + '\n')

    # ---- execution log template
    with open(os.path.join(DOCS, 'tests', 'execution-log-template.csv'), 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f)
        w.writerow(['Test case', 'Mode', 'Title', 'Type', 'Priority', 'Automation', 'Result (Pass/Fail/Blocked/NA)', 'Tester', 'Date', 'Build (version + migration)', 'Browser / device', 'Defect ID', 'Notes'])
        for c in cases.values():
            w.writerow([c['id'], c['mode'], c['title'], c['type'], c['prio'], short_auto(c['auto']), '', '', '', '', '', '', ''])

    # ---- SRS-complete
    parts = []
    for name in SRS_ORDER:
        p = os.path.join(DOCS, 'srs', name)
        if os.path.exists(p):
            parts.append(read(p).strip())
    with open(os.path.join(DOCS, 'SRS-complete.md'), 'w', encoding='utf-8') as f:
        f.write('<!-- Generated by docs/build-docs.py from docs/srs/SRS-*.md. Do not edit. -->\n\n' + '\n\n---\n\n'.join(parts) + '\n')

    # ---- numbers in docs/README.md (between the <!--stats--> markers)
    rp = os.path.join(DOCS, 'README.md')
    if os.path.exists(rp):
        rows = ['| Document set | Requirements | Test cases | P1 cases |', '|---|---|---|---|']
        groups = [('Personal A (dashboard, calendar, reminders, tasks, notes, documents, contacts, focus)', 'SRS-personal-a.md', 'TC-personal-a.md'),
                  ('Personal B (money, subscriptions, bills, goals, habits, health, analytics, split, purchases, Lumi)', 'SRS-personal-b.md', 'TC-personal-b.md'),
                  ('Work', 'SRS-work.md', 'TC-work.md'), ('Study', 'SRS-study.md', 'TC-study.md'), ('Platform', 'SRS-platform.md', 'TC-platform.md')]
        for label, sf, tf in groups:
            rr = [r for r in reqs.values() if r['file'] == sf]
            cc = by_file.get(tf, [])
            rows.append(f"| {label} | {len(rr)} | {len(cc)} | {sum(1 for c in cc if c['prio'].startswith('P1'))} |")
        rows.append(f"| **Total** | **{len(reqs)}** | **{len(cases)}** | **{sum(1 for c in cases.values() if c['prio'].startswith('P1'))}** |")
        cov = sum(1 for r in reqs if covers.get(r))
        block = '<!--stats-->\n' + '\n'.join(rows) + f"\n\nEvery requirement has at least one test case ({cov} of {len(reqs)}; see [05-TRACEABILITY.md](05-TRACEABILITY.md)). Generated by `python3 docs/build-docs.py`.\n<!--/stats-->"
        txt = read(rp)
        txt = re.sub(r'<!--stats-->.*?<!--/stats-->', lambda m: block, txt, flags=re.S)
        with open(rp, 'w', encoding='utf-8') as f:
            f.write(txt)

    # ---- summary
    print(f'requirements: {len(reqs)}  test cases: {len(cases)}  covered: {sum(1 for r in reqs if covers.get(r))}  gaps: {len(gaps)}  unknown refs: {len(unknown)}  no-req cases: {len(no_req)}  duplicate ids: {len(dupes)}')
    for n, lst in by_file.items():
        print(f'  {n}: {len(lst)} cases')
    for a, v in areas.items():
        print(f'  {a}: {v["covered"]}/{v["n"]}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
